name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"

  release:
    types:
      - published

env:
  NODE_VERSION_FILE: .nvmrc
  SITE_URL: "https://shubydo.com"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: "github-pages"
      url: ${{ env.SITE_URL }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: ./actions/install_dependencies
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: "Deploy to GitHub Pages"
        run: |
          echo "Configuring git for deployment"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GH_PAGES_ACTION_TOKEN }}@github.com/shubydo/shubydo.github.io.git

          echo "Deploying to GitHub Pages..."
          yarn deploy
