name: Pull Request

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION_FILE: .nvmrc

# default to bash
defaults:
  run:
    shell: bash

# Build and test the project. Output test results to the PR.
jobs:
  dependencies:
    runs-on: ubuntu-latest
    name: Install dependencies
    steps:
      - uses: ./actions/install_dependencies
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

  test:
    name: Test
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: "yarn install"
        run: |
          yarn

      # Push jest test results to the PR.
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          test-script: yarn test
          prnumber: ${{ github.event.pull_request.number }}
