name: Pull Request

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: 19.2.0

# default to bash
defaults:
  run:
    shell: bash

# Build and test the project. Output test results to the PR.
jobs:
  dependencies:
    runs-on: ubuntu-latest
    name: Install dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: ${{ env.NODE_VERSION }}
          package-manager: yarn
      - run: |
          yarn
        name: "yarn install"

      # Cache node modules
      - uses: actions/cache@v2
        name: Cache node modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  test:
    name: Test
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          yarn
        name: Install dependencies

      # Push jest test results to the PR.
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          test-script: yarn test
          prnumber: ${{ github.event.pull_request.number }}
